openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/auth/code/send:
    post:
      summary: 'Отправить код'
      operationId: ''
      description: 'На электронную почту пользователя отправляется код подтверждения'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: null
                  message: OK
                properties:
                  data:
                    type: string
                    example: null
                    description: ''
                  message:
                    type: string
                    example: OK
                    description: ''
      tags:
        - Авторизация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                  description: 'Must be a valid email address.'
                  example: rex16@example.com
              required:
                - subject
      security: []
  /api/auth/code/confirm:
    post:
      summary: 'Проверить код'
      operationId: ''
      description: 'Проверка отправленного кода'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: null
                  message: OK
                properties:
                  data:
                    type: string
                    example: null
                    description: ''
                  message:
                    type: string
                    example: OK
                    description: ''
      tags:
        - Авторизация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                  description: 'Must be a valid email address.'
                  example: shyanne.cummerata@example.org
                code:
                  type: string
                  description: 'Must match the regex /^([0-9]*)$/. Must be 4 digits.'
                  example: '5053'
              required:
                - subject
                - code
      security: []
  /api/auth/register:
    post:
      summary: 'Зарегистрировать пользователя'
      operationId: ''
      description: 'Эндпоинт повторно проверяет данные вместе с паролем и авторизует пользователя'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    token: 1|YS6hb29ybsALdzkAKghukjgny0Fzju3awd6iRTvvd4155e61
                  message: OK
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: 1|YS6hb29ybsALdzkAKghukjgny0Fzju3awd6iRTvvd4155e61
                        description: ''
                  message:
                    type: string
                    example: OK
                    description: ''
        400:
          description: 'Отправлен не валидный код'
          content:
            application/json:
              schema:
                type: object
                example:
                  data: null
                  message: 'Код устарел'
                properties:
                  data:
                    type: string
                    example: null
                    description: ''
                  message:
                    type: string
                    example: 'Код устарел'
                    description: ''
      tags:
        - Авторизация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters. Must be at least 1 character.'
                  example: tsrtlgzxdsmjnndfzyseldbahufeyiq
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters. Must be at least 3 characters.'
                  example: delores.gottlieb@example.net
                phone:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 20 characters.'
                  example: vyyrbosi
                password:
                  type: string
                  description: 'Must not be greater than 255 characters. Must be at least 6 characters.'
                  example: CjxZC=-WuoLXqk<X~
                birthday:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-05-30T08:07:16'
                gender:
                  type: string
                  description: ''
                  example: female
                  enum:
                    - male
                    - female
                is_notifiable:
                  type: boolean
                  description: ''
                  example: true
                location_id:
                  type: string
                  description: ''
                  example: null
              required:
                - name
                - email
                - phone
                - password
                - birthday
                - gender
                - is_notifiable
      security: []
  /api/auth/login:
    post:
      summary: 'Войти в аккаунт'
      operationId: ''
      description: 'Эндпоинт необходим для аутентификации пользователя в системе'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    token: 1|zoBOyNT0SVZAX2yII1hsDs0kmOdvFERU0WAFvIjz370200e1
                  message: 'Успешный вход.'
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: 1|zoBOyNT0SVZAX2yII1hsDs0kmOdvFERU0WAFvIjz370200e1
                        description: ''
                  message:
                    type: string
                    example: 'Успешный вход.'
                    description: ''
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: null
                  message: 'Ошибка авторизации. Проверьте правильно ли указаны логин или пароль'
                properties:
                  data:
                    type: string
                    example: null
                    description: ''
                  message:
                    type: string
                    example: 'Ошибка авторизации. Проверьте правильно ли указаны логин или пароль'
                    description: ''
      tags:
        - Авторизация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: emory.homenick@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: '[vrA0]Sau8*{~F'
              required:
                - email
                - password
      security: []
  /api/auth/forgot:
    post:
      summary: 'Изменить пароль'
      operationId: ''
      description: 'Эндпоинт необходим для изменения пароля'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: null
                  message: 'Пароль успешно изменен'
                properties:
                  data:
                    type: string
                    example: null
                  message:
                    type: string
                    example: 'Пароль успешно изменен'
      tags:
        - Авторизация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: haley.demetris@example.net
                code:
                  type: string
                  description: 'Must match the regex /^([0-9]*)$/. Must be 4 digits.'
                  example: '1909'
                password:
                  type: string
                  description: 'This field is required when <code>password_confirmation</code> is present. Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: "b-?*`i'(Ed{$u>=sh{"
                password_confirmation:
                  type: string
                  description: 'This field is required when <code>password</code> is present.  The value and <code>password</code> must match. Must be at least 6 characters.'
                  example: btrsfnxexzcwejjmiijplyilvifieqvvltluvmndalltfwnprvg
              required:
                - email
                - code
                - password
      security: []
  /api/user:
    get:
      summary: 'Список пользователей'
      operationId: ''
      description: 'Отобразить список зарегистрированных пользователей'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Пользователи
      security: []
  '/api/user/detail/{user_id}':
    get:
      summary: 'Профиль пользователя'
      operationId: ''
      description: 'Отобразить профиль пользователя'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Пользователи
      security: []
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user/update:
    post:
      summary: 'Редактирование профиля'
      operationId: ''
      description: 'Редактирование профиля авторизированного пользователя'
      parameters: []
      responses: {  }
      tags:
        - Пользователи
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters. Must be at least 1 character.'
                  example: iicrrgakhuujiqdeyvhwabmhwsultdxeitqrhmyagvfpufhcbjtsyubzndwmgusbjsktnmgkqcwkdffqgxgglbf
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters. Must be at least 3 characters.'
                  example: ola.keebler@example.com
                phone:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 14 characters.'
                  example: alxy
                password:
                  type: string
                  description: 'Must not be greater than 255 characters. Must be at least 6 characters.'
                  example: '_F=HG?('
                birthday:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-05-30T08:07:16'
                gender:
                  type: string
                  description: ''
                  example: female
                  enum:
                    - male
                    - female
                about:
                  type: string
                  description: ''
                  example: commodi
                is_notifiable:
                  type: boolean
                  description: ''
                  example: false
                location_id:
                  type: string
                  description: ''
                  example: null
      security: []
tags:
  -
    name: Авторизация
    description: 'API предназначенное для авторизации пользователя'
  -
    name: Пользователи
    description: 'API для взаимодействия с профилями пользователей'
